# compile.do - compile the RV32IMscMCU design + testbench
#
# Reference: Auxiliary/Lab 5 - as submitted/SIM/RV32IM_sc/compile.do
# Changes:   paths retargeted to DUT/RV32IMscMCU, and two files added -
#            RV32IMscMCU.vhd (the board-facing structural top, Final Project
#            §3) and tb_RV32IMscMCU.vhd (the name the submission table mandates).
#
# -2008 is mandatory: EXECUTE.vhd uses process(all) and both structural tops
# use if/else generate.
# Compile order matters - packages before everything that uses them, and
# RV32IM_CORE before the wrapper that instantiates it.
#
# Run with the working directory set to SIM/RV32IMscMCU.

vlib work
vmap work work

# packages first - everything depends on them
vcom -2008 ../../DUT/RV32IMscMCU/cond_compilation_package.vhd
vcom -2008 ../../DUT/RV32IMscMCU/const_package.vhd
vcom -2008 ../../DUT/RV32IMscMCU/aux_package.vhd

# multiplier, submodules, core, MCU top, testbench
vcom -2008 ../../DUT/RV32IMscMCU/MUL16.vhd
vcom -2008 ../../DUT/RV32IMscMCU/CONTROL.vhd
vcom -2008 ../../DUT/RV32IMscMCU/IFETCH.vhd
vcom -2008 ../../DUT/RV32IMscMCU/IDECODE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/EXECUTE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/DMEMORY.vhd
vcom -2008 ../../DUT/RV32IMscMCU/PLL.vhd
vcom -2008 ../../DUT/RV32IMscMCU/RV32IM_CORE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/RV32IMscMCU.vhd
vcom -2008 ../../TB/RV32IMscMCU/tb_RV32IMscMCU.vhd

# ---- directed ISA test (Phase 2) ----
# The expected-store package is generated by tools/gen_isa_test.py and must be
# compiled before the testbench that uses it.
vcom -2008 ../../TB/RV32IMscMCU/isa_expected_pkg.vhd
vcom -2008 ../../TB/RV32IMscMCU/tb_isa_directed.vhd
