# compile.do - compile the RV32IMscMCU design + testbench
#
# Reference: Auxiliary/Lab 5 - as submitted/SIM/RV32IM_sc/compile.do
# Changes:   paths retargeted to DUT/RV32IMscMCU, and two files added -
#            RV32IMscMCU.vhd (the board-facing structural top, Final Project
#            §3) and tb_RV32IMscMCU.vhd (the name the submission table mandates).
#
# -2008 is mandatory: EXECUTE.vhd uses process(all) and both structural tops
# use if/else generate.
# Compile order matters - packages before everything that uses them, leaf modules
# before the units that instantiate them, and RV32IM_CORE before the wrapper.
#
# Run with the working directory set to SIM/RV32IMscMCU.

vlib work
vmap work work

# packages first - everything depends on them
vcom -2008 ../../DUT/RV32IMscMCU/cond_compilation_package.vhd
vcom -2008 ../../DUT/RV32IMscMCU/const_package.vhd
vcom -2008 ../../DUT/RV32IMscMCU/aux_package.vhd

# leaf modules, in dependency order. ADDR_DECODER is here rather than at the end
# because RV32IMscMCU.vhd instantiates it (Phase 5B); SYNC is not instantiated by
# anything yet but is compiled so its own testbench can run and so the phase that
# does instantiate it finds it already in the library.
vcom -2008 ../../DUT/RV32IMscMCU/MUL16.vhd
vcom -2008 ../../DUT/RV32IMscMCU/CONTROL.vhd
vcom -2008 ../../DUT/RV32IMscMCU/IFETCH.vhd
vcom -2008 ../../DUT/RV32IMscMCU/IDECODE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/EXECUTE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/DMEMORY.vhd
vcom -2008 ../../DUT/RV32IMscMCU/PLL.vhd
vcom -2008 ../../DUT/RV32IMscMCU/SYNC.vhd
vcom -2008 ../../DUT/RV32IMscMCU/ADDR_DECODER.vhd
# Phase 6A. HEX_DECODER.vhd is the students' Lab 4 file used as is - its body is
# byte-identical to Auxiliary/Lab 5/Auxilary/Lab4/DUT/hex_decoder.vhd, md5
# 56f2f16645e9bb4643c3a113c36e49c4. Only a provenance header was added.
vcom -2008 ../../DUT/RV32IMscMCU/HEX_DECODER.vhd
vcom -2008 ../../DUT/RV32IMscMCU/GPO_PORT.vhd

# core, then the MCU top that instantiates the core and the decoder
vcom -2008 ../../DUT/RV32IMscMCU/RV32IM_CORE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/RV32IMscMCU.vhd

# testbenches
vcom -2008 ../../TB/RV32IMscMCU/tb_RV32IMscMCU.vhd
vcom -2008 ../../TB/RV32IMscMCU/tb_sync.vhd

# Phase 5A: exhaustive over all 16384 addresses of the clause 3 data address
# space, about 16 us of simulated time, no memory images needed.
vcom -2008 ../../TB/RV32IMscMCU/tb_addr_decoder.vhd

# Phase 5B: runs the supplied GPIO test0 program, so this one DOES need the
# images staged - see the header of run_mmio.do.
vcom -2008 ../../TB/RV32IMscMCU/tb_mmio_alias.vhd

# Phase 6A: same staging as tb_mmio_alias, so if that one runs, this one runs.
vcom -2008 ../../TB/RV32IMscMCU/tb_gpio.vhd

# ---- directed ISA test (Phase 2) ----
# The expected-store package is generated by tools/gen_isa_test.py and must be
# compiled before the testbench that uses it.
vcom -2008 ../../TB/RV32IMscMCU/isa_expected_pkg.vhd
vcom -2008 ../../TB/RV32IMscMCU/tb_isa_directed.vhd
