# compile.do - compile the RV32IMscMCU design + testbench
#
# Reference: Auxiliary/Lab 5 - as submitted/SIM/RV32IM_sc/compile.do
# Changes:   paths retargeted to DUT/RV32IMscMCU, and two files added -
#            RV32IMscMCU.vhd (the board-facing structural top, Final Project
#            §3) and tb_RV32IMscMCU.vhd (the name the submission table mandates).
#
# -2008 is mandatory: EXECUTE.vhd uses process(all) and both structural tops
# use if/else generate.
# Compile order matters - packages before everything that uses them, leaf modules
# before the units that instantiate them, and RV32IM_CORE before the wrapper.
#
# Run with the working directory set to SIM/RV32IMscMCU.

vlib work
vmap work work

# packages first - everything depends on them
vcom -2008 ../../DUT/RV32IMscMCU/cond_compilation_package.vhd
vcom -2008 ../../DUT/RV32IMscMCU/const_package.vhd
vcom -2008 ../../DUT/RV32IMscMCU/aux_package.vhd

# leaf modules, in dependency order. ADDR_DECODER is here because RV32IMscMCU.vhd
# instantiates it (Phase 5B). SYNC is no longer an orphan either - Phase 7B1's
# DIV_UNIT instantiates it four times, which is its first real use.
vcom -2008 ../../DUT/RV32IMscMCU/MUL16.vhd
vcom -2008 ../../DUT/RV32IMscMCU/CONTROL.vhd
vcom -2008 ../../DUT/RV32IMscMCU/IFETCH.vhd
vcom -2008 ../../DUT/RV32IMscMCU/IDECODE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/EXECUTE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/DMEMORY.vhd
vcom -2008 ../../DUT/RV32IMscMCU/PLL.vhd
# Phase 4B. PLL_GEN is PLL with the ratio as generics; CLOCK_TREE is Figure 1's
# block built from three of them. Both compile without altera_mf because at
# MODELSIM = 1 neither instantiates altpll - the same bypass the core already
# uses. PLL_GEN must come before CLOCK_TREE, which instantiates it.
vcom -2008 ../../DUT/RV32IMscMCU/PLL_GEN.vhd
vcom -2008 ../../DUT/RV32IMscMCU/CLOCK_TREE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/SYNC.vhd
# Phase 7A. Figure 9's division accelerator, now instantiated by DIV_UNIT below.
vcom -2008 ../../DUT/RV32IMscMCU/DIV_ACCEL.vhd
# Phase 7B1. DIV_UNIT instantiates DIV_ACCEL and SYNC, so both must precede it.
vcom -2008 ../../DUT/RV32IMscMCU/DIV_UNIT.vhd
vcom -2008 ../../DUT/RV32IMscMCU/ADDR_DECODER.vhd
# Phase 8A. The Basic Timer core -- skeleton from Auxiliary/Lab4/DUT/pwm.vhd.
# A leaf until Phase 8B wires it in; compiled so its testbench runs.
vcom -2008 ../../DUT/RV32IMscMCU/BASIC_TIMER.vhd
# Phase 6A. HEX_DECODER.vhd is the students' Lab 4 file used as is - its body is
# byte-identical to Auxiliary/Lab4/DUT/hex_decoder.vhd, md5
# 56f2f16645e9bb4643c3a113c36e49c4. Only a provenance header was added.
vcom -2008 ../../DUT/RV32IMscMCU/HEX_DECODER.vhd
vcom -2008 ../../DUT/RV32IMscMCU/GPO_PORT.vhd
# Phase 6B. BIDIRPIN.vhd is the students' Lab 3 file used as is - its body is
# byte-identical to Auxiliary/Lab 5/Auxilary/Lab3/DUT/BidirPin.vhd (since deleted from the tree), md5
# ab12d81dcdc85d91071b077359833bbd. It is the block Figure 1's bidirectional-bus
# link points at, and Figure 5 draws it as the buffer on CS.MemRead.
vcom -2008 ../../DUT/RV32IMscMCU/BIDIRPIN.vhd

# core, then the MCU top that instantiates the core and the decoder
vcom -2008 ../../DUT/RV32IMscMCU/RV32IM_CORE.vhd
vcom -2008 ../../DUT/RV32IMscMCU/RV32IMscMCU.vhd

# testbenches
vcom -2008 ../../TB/RV32IMscMCU/tb_RV32IMscMCU.vhd
vcom -2008 ../../TB/RV32IMscMCU/tb_sync.vhd

# Phase 7A: zero setup, no memory images. Runs all 65536 operand pairs at N=8
# plus the N=32 corners. See run_div.do for the runtime.
vcom -2008 ../../TB/RV32IMscMCU/tb_div_accel.vhd

# Phase 4B: also zero setup. Note it does NOT verify the PLLs - altpll is not
# instantiated at MODELSIM = 1. See run_clock.do.
vcom -2008 ../../TB/RV32IMscMCU/tb_clock_tree.vhd

# Phase 7B1: zero setup. Two coprime clocks, signed and unsigned div/rem.
vcom -2008 ../../TB/RV32IMscMCU/tb_div_unit.vhd

# Phase 8A: zero setup. F16/F17, prescaler, PWM duty, capture, BTINT select.
vcom -2008 ../../TB/RV32IMscMCU/tb_basic_timer.vhd

# Phase 8B: needs the generated timer images staged (SIM/RV32IMscMCU/timer/).
# Runs at either G_ISA_REPAIR setting, like the directed GPIO test.
vcom -2008 ../../TB/RV32IMscMCU/tb_timer_mmio.vhd

# Phase 5A: exhaustive over all 16384 addresses of the clause 3 data address
# space, about 16 us of simulated time, no memory images needed.
vcom -2008 ../../TB/RV32IMscMCU/tb_addr_decoder.vhd

# Phase 5B: runs the supplied GPIO test0 program, so this one DOES need the
# images staged - see the header of run_mmio.do.
vcom -2008 ../../TB/RV32IMscMCU/tb_mmio_alias.vhd

# Phase 6A: same staging as tb_mmio_alias, so if that one runs, this one runs.
vcom -2008 ../../TB/RV32IMscMCU/tb_gpio.vhd

# Phase 6B: this one needs GPIO **test1**'s images, not test0's - the only script
# in the set with different staging. See the header of run_gpio_read.do.
vcom -2008 ../../TB/RV32IMscMCU/tb_gpio_read.vhd

# ---- directed GPIO test (closes G-406 and G-407) ----
# Generated by tools/gen_gpio_test.py, like the ISA suite. The package must be
# compiled before the testbench that uses it. This is the one GPIO test that runs
# at either G_ISA_REPAIR setting and needs no benchmark image.
vcom -2008 ../../TB/RV32IMscMCU/gpio_expected_pkg.vhd
vcom -2008 ../../TB/RV32IMscMCU/tb_gpio_directed.vhd

# ---- directed ISA test (Phase 2) ----
# The expected-store package is generated by tools/gen_isa_test.py and must be
# compiled before the testbench that uses it.
vcom -2008 ../../TB/RV32IMscMCU/isa_expected_pkg.vhd
vcom -2008 ../../TB/RV32IMscMCU/tb_isa_directed.vhd
