# run_timer_mmio.do - Phase 8B: the Basic Timer through the MCU's own bus
#
# Run compile.do first.
#
# ####################################################################
# # Uses the GENERATED timer images from SIM\RV32IMscMCU\timer\ -      #
# # STAGED AUTOMATICALLY (since Phase 13), and every other script     #
# # stages its own, so nothing has to be put back afterwards.         #
# ####################################################################
#
# Regenerate them with:  python3 tools/gen_timer_test.py
#
# WHAT THIS PROVES: the Phase 8B WIRING only. The timer core itself was proven
# cycle-exact by run_timer.do (tb_basic_timer + model_basic_timer, eight
# mutations caught). Here a 113-instruction program - generated by
# tools/gen_timer_test.py, expectations cross-derived by executing it against
# the vetted Timer model - configures the timer over the bus, reads all five
# registers back (BTCTL2 written via its ODD byte address 0x201D), echoes
# test4's capture bug at MCU level (source parked on GND captures NOTHING),
# forces the edge test4 meant (CAPISEL GND->VCC), reads a stable K back twice,
# and starts PWM. The bench then measures PWM_o at the PIN: high 10 / low 31,
# period 41 - Lab 4's pwm.vhd semantics arriving at a board pin through every
# layer built since Phase 5A.
#
# EXPECTED NUMBERS
#   VERDICT: PASS, failed 0, 7 scored stores, captured K in 1..60 (the
#   interpreter predicts 10 - see SIM/RV32IMscMCU/timer/listing.txt), and two
#   exact 10/31 PWM periods.

onerror {quit -code 1}

# Staging, done here so the flow has no manual copy step (Phase 13).
# Images: generated: tools/gen_timer_test.py
file copy -force timer/ITCM.hex C:/TestPrograms/Quartus21_1/app_bin/ITCM.hex
file copy -force timer/DTCM.hex C:/TestPrograms/Quartus21_1/app_bin/DTCM.hex

# Development-only testbench: compile.do compiles just the clause 10
# official testbench (tb_RV32IMscMCU), so this script compiles its own.
vcom -2008 ../../TB/RV32IMscMCU/tb_timer_mmio.vhd

vsim -t ns -gMODELSIM=1 work.tb_timer_mmio
run -all

echo ""
echo "Read the SUMMARY block above. Expected: VERDICT: PASS, failed 0,"
echo "captured K around 10, PWM widths exactly 10 and 31."
echo ""
echo "If S1..S4 fail: the timer's write or read path on the bus - check the"
echo "rd_en_w terms and the one-hot warning from onehot_check."
echo "If only S2 fails: the lane1 term on the BTCTL word (odd-address write)."
echo "If S3/S4 read back 8 bits only: the word registers went through WEXT's"
echo "zero-extension instead of driving rd_word_w directly."
echo "If S5 is non-zero: a capture fired from a GND-parked source."
echo "If S6/S7 differ: the BidirPin reader for BTCAPR is not stable."
echo "If PWM widths are 10/30 or 11/31: the F17 wrap moved by one count."
