# run_intr_core.do - Phase 9B: the CPU side of the interrupt protocol
#
# Run compile.do first.
#
# ######################################################################
# # STAGING REQUIRED, like run_mmio/run_gpio/run_timer_mmio:           #
# #   copy SIM\RV32IMscMCU\intr\ITCM.hex and DTCM.hex into app_bin     #
# #   (C:\TestPrograms\Quartus21_1\app_bin\). NOT the gpio or timer    #
# #   images - the first FAIL line will say so if they are stale.      #
# # Runs at EITHER G_ISA_REPAIR setting.                               #
# ######################################################################
#
# WHAT THIS IS
#   RV32IM_CORE alone, with the TESTBENCH playing the interrupt controller
#   (tb_intr_core.vhd drives intr_i, checks the one-cycle INTA pulse, and
#   pushes TYPE on the data bus in the following cycle - INTERRUPT_CTRL's
#   exact behaviour, verified separately by run_intc.do). The program was
#   generated by tools/gen_intr_core_test.py, whose interpreter emulates
#   the whole protocol as the second derivation of every expected value.
#
# WHAT PASS MEANS
#   - REQ p15's two-cycle entry: GIE (gp[0]) cleared IN HW (the ISR reads
#     gp = 0), TYPE captured from the DATA bus, the vector fetched from
#     the DTCM table THE PROGRAM ITSELF WROTE, tp = the return address.
#   - reti (jalr zero,0(tp)) sets GIE back IN HW and execution resumes:
#     main reads gp = 1 after every round, and tp in main equals tp in
#     the ISR (ranges printed in the summary).
#   - Two DIFFERENT vectors reach two different handlers (TYPE 14h -> the
#     KEY1 ISR, TYPE 10h -> the BT ISR's 0xB7 marker).
#   - F13: an interrupt raised the moment the div appears is DEFERRED
#     through the div, the adjacent rem AND the busy tail - the summary
#     prints the measured deferral (expect well above the 12-cycle floor)
#     - and both results are exact afterwards (142 and 6).
#   - Exactly 16 scored stores: the annulled instruction at the return
#     address retires exactly once.
#
# WHAT PASS DOES NOT MEAN
#   Nothing about INTERRUPT_CTRL itself (run_intc.do is its leaf test) and
#   nothing about the two sides wired together on the bus - that is Phase
#   9C, whose test drives the REAL controller and the REAL CS_INTC.

onerror {quit -code 1}

# Development-only testbench: compile.do compiles just the clause 10
# official testbench (tb_RV32IMscMCU), so this script compiles its own.
vcom -2008 ../../TB/RV32IMscMCU/tb_intr_core.vhd

vsim -t ns work.tb_intr_core
run -all

echo ""
echo "Read the SUMMARY block above. Expected: VERDICT: PASS, failed 0, and"
echo "sane printed values: tp1 in 44..48, tp3 in 100..124, deferral >= 12."
echo ""
echo "If the program never finishes: wrong images staged (intr\\, not gpio\\)."
echo "If gp-inside-ISR is 1: GIE was not cleared in HW (rule e broke)."
echo "If gp-after-reti is 0: reti did not set GIE in HW (rule f broke)."
echo "If [0x188] is not 0xB7: TYPE 10h did not select vector word 4 - check"
echo "  the type_q capture and the Cycle-2 DTCM address mux."
echo "If the R3 deferral is tiny: the accept gate ignored div_start/div_busy"
echo "  (F13). If 142/6 are wrong: the entry corrupted an in-flight divide."
echo "If stores != 16: the entry-annul gating leaked or swallowed a retire."
