--============================================================================
-- isa_expected_pkg — GENERATED by tools/gen_isa_test.py. Do not edit by hand.
--
-- The complete expected store sequence of the directed ISA test, in bus order.
-- The testbench snoops MemWrite_ctrl_o / dtcm_addr_o / dtcm_data_wr_o and
-- compares each store against the next entry here, so both the value and the
-- ordering are checked.
--
-- Entries marked "setup" are scratch stores a case performs while preparing its
-- operands. They are real stores on the bus, so they must appear in the
-- sequence, but a mismatch on one of them points at the store path rather than
-- at the instruction under test.
--
-- Entries marked "DEFECT" are expected to FAIL on the unfixed core. That is the
-- point of the suite: 20 of 43 stores should mismatch today. See
-- SIM/RV32IMscMCU/isa/listing.txt for the reason attached to each one.
--
-- Cross-checked against a reference RV32IM interpreter in the generator, so the
-- values below are what a conformant core produces, not what this core does.
--============================================================================
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

package isa_expected_pkg is

	constant NAME_LEN : natural := 13;

	type expected_t is record
		addr	: natural;										-- DTCM word index
		data	: STD_LOGIC_VECTOR(31 DOWNTO 0);
		name	: string(1 to NAME_LEN);
	end record;

	type expected_array_t is array (natural range <>) of expected_t;

	constant STORE_COUNT : natural := 43;

	-- How many of the stores above are expected to MISMATCH, in each of the two
	-- configurations of cond_compilation_package.G_ISA_REPAIR. The testbench picks
	-- the right one and compares its own tally against it, so neither number can
	-- drift out of step with the suite.
	--
	--   G_ISA_REPAIR = FALSE  the core exactly as LAB5 submitted it
	constant EXPECTED_DEFECT_COUNT : natural := 20;
	--   G_ISA_REPAIR = TRUE   the seven Phase 3A repairs applied. The remainder are
	--                         blocked on work outside Phase 3A: G-307, G-308, G-309, G-326
	constant EXPECTED_DEFECT_COUNT_REPAIRED : natural := 10;

	constant EXPECTED : expected_array_t(0 to STORE_COUNT-1) := (
		(   0, x"0000002A", "addi         "),	--   0       
		(   1, x"FFFFFFFF", "addi_neg     "),	--   1       
		(   2, x"00000008", "add          "),	--   2       
		(   3, x"00000002", "sub          "),	--   3       
		(   4, x"00000030", "and          "),	--   4       
		(   5, x"000000FC", "or           "),	--   5       
		(   6, x"000000CC", "xor          "),	--   6       
		(   7, x"0000000F", "andi         "),	--   7 DEFECT
		(   8, x"000000FF", "ori          "),	--   8 DEFECT
		(   9, x"000000F0", "xori         "),	--   9       
		(  10, x"00000001", "slti         "),	--  10       
		(  11, x"00000001", "slti_neg     "),	--  11       
		(  12, x"00000000", "sltiu        "),	--  12 DEFECT
		(  13, x"00000001", "slt          "),	--  13       
		(  14, x"00000000", "sltu         "),	--  14 DEFECT
		(  15, x"00000010", "sll          "),	--  15       
		(  16, x"00000010", "slli         "),	--  16       
		(  17, x"08000000", "srli         "),	--  17       
		(  18, x"F8000000", "srai         "),	--  18 DEFECT
		(  19, x"F8000000", "sra          "),	--  19 DEFECT
		(  20, x"12345000", "lui          "),	--  20 DEFECT
		(  21, x"00000120", "auipc        "),	--  21       
		( 200, x"000002AA", "scratch200   "),	--  22 setup 
		( 201, x"00000155", "scratch201   "),	--  23 setup 
		(  22, x"000002AA", "lw_offset    "),	--  24 DEFECT
		(  23, x"0000007F", "sb_then_lbu  "),	--  25 DEFECT
		(  24, x"0000000C", "mul_small    "),	--  26       
		(  25, x"2468ACF0", "mul_wide     "),	--  27 DEFECT
		(  26, x"80000000", "mul_hi_low   "),	--  28 DEFECT
		(  27, x"01234567", "mulh         "),	--  29 DEFECT
		(  28, x"01234567", "mulhu        "),	--  30 DEFECT
		(  29, x"01234567", "mulhsu       "),	--  31 DEFECT
		(  30, x"0000000E", "div          "),	--  32 DEFECT
		(  31, x"0000000E", "divu         "),	--  33 DEFECT
		(  32, x"00000002", "rem          "),	--  34 DEFECT
		(  33, x"00000002", "remu         "),	--  35 DEFECT
		(  34, x"0000000A", "beq_taken    "),	--  36       
		(  35, x"0000000A", "bne_taken    "),	--  37       
		(  36, x"0000000A", "blt_taken    "),	--  38       
		(  37, x"0000000A", "bge_taken    "),	--  39       
		(  38, x"0000000B", "bltu_nottaken"),	--  40 DEFECT
		(  39, x"0000000A", "bgeu_taken   "),	--  41 DEFECT
		(  40, x"0000032C", "jal_link     ")	--  42       
	);

end package isa_expected_pkg;
