--============================================================================
-- Advanced CPU architecture and Hardware Accelerators Lab 361-1-4693 BGU
-- Final Project 2026 -- custom KEY1 PWM-mode demo (pipelined MCU)
--
-- HOW TO RUN
--   SIM/RV32IMpipelinedMCU/run_pwm_modes.do
--   Stages SIM/RV32IMscMCU/pwm_modes/ (generated by tools/gen_pwm_modes.py)
--   and passes MODELSIM=1.
--
-- WHAT THIS PROVES
--   The custom firmware in PWM_modes/pwm_modes.s, running on the full MCU:
--   KEY1 through the interrupt controller (release edge, software KEY1IFG
--   clear), HEX0/LEDR showing the mode, and PWM_o at GPIO[9] carrying
--   Figure 8 Mode0, Figure 8 Mode1, then Lab 4 Toggle.
--
--   Period/duty are test4's PWM constants: FREQ_5K=500, BTCMPR1=250,
--   BTSSEL=/8. Mode0 high/low = 2000/2008 pclk; Mode1 is the complement;
--   Toggle is one edge per wrap so each phase is 4008 pclk.
--============================================================================
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
use std.env.all;
USE work.cond_compilation_package.all;
USE work.aux_package.all;


ENTITY tb_pwm_modes IS
	generic(
		MODELSIM	: integer := G_MODELSIM
	);
END tb_pwm_modes;


ARCHITECTURE test OF tb_pwm_modes IS

	constant CLK_PERIOD	: time := 100 ns;

	SIGNAL clk		: STD_LOGIC := '0';
	SIGNAL rst		: STD_LOGIC := '1';
	SIGNAL running	: BOOLEAN := TRUE;

	SIGNAL key_pins	: STD_LOGIC_VECTOR(3 DOWNTO 1) := "111";
	SIGNAL ledr10	: STD_LOGIC_VECTOR(9 DOWNTO 0);
	SIGNAL ledr		: STD_LOGIC_VECTOR(7 DOWNTO 0);
	SIGNAL hex0, hex1, hex2, hex3, hex4, hex5 : STD_LOGIC_VECTOR(6 DOWNTO 0);
	SIGNAL pwm		: STD_LOGIC;
	SIGNAL pwm_seen	: BOOLEAN := FALSE;

	function seg7(constant d : natural) return STD_LOGIC_VECTOR is
	begin
		case d is
			when 0  => return "1000000";
			when 1  => return "1111001";
			when 2  => return "0100100";
			when 3  => return "0110000";
			when 4  => return "0011001";
			when 5  => return "0010010";
			when 6  => return "0000010";
			when 7  => return "1111000";
			when 8  => return "0000000";
			when 9  => return "0010000";
			when 10 => return "0001000";
			when 11 => return "0000011";
			when 12 => return "1000110";
			when 13 => return "0100001";
			when 14 => return "0000110";
			when others => return "0001110";
		end case;
	end function seg7;

BEGIN
	MCU : RV32IMpipelinedMCU
	generic map(
		RST_ACTIVE_LOW	=> FALSE,
		MODELSIM		=> MODELSIM
	)
	PORT MAP (
		clk_i			=> clk,
		rst_i			=> rst,
		KEY_i			=> key_pins,
		LEDR_o			=> ledr10,
		HEX0_o			=> hex0,
		HEX1_o			=> hex1,
		HEX2_o			=> hex2,
		HEX3_o			=> hex3,
		HEX4_o			=> hex4,
		HEX5_o			=> hex5,
		PWM_o			=> pwm
	);

	ledr <= ledr10(7 DOWNTO 0);

	clk_gen : process
	begin
		while running loop
			clk <= '1'; wait for CLK_PERIOD/2;
			clk <= '0'; wait for CLK_PERIOD/2;
		end loop;
		wait;
	end process clk_gen;

	rst <= '1', '0' after 80 ns;

	pwm_watch : process(clk)
	begin
		if falling_edge(clk) and rst = '0' then
			if pwm = '1' then
				pwm_seen <= TRUE;
			end if;
		end if;
	end process pwm_watch;

	stim : process
		variable p, f : natural := 0;

		procedure chk(constant ok : boolean; constant msg : string) is
		begin
			if ok then p := p + 1;
			else
				f := f + 1;
				report "FAIL " & msg severity error;
			end if;
		end procedure chk;

		procedure settle(constant n : IN NATURAL) is
		begin
			for i in 1 to n loop wait until falling_edge(clk); end loop;
		end procedure settle;

		procedure press(constant k : IN NATURAL) is
		begin
			wait until falling_edge(clk);
			key_pins(k) <= '0';
			settle(6);
			key_pins(k) <= '1';
		end procedure press;

		procedure chk_hex(signal   h : IN STD_LOGIC_VECTOR(6 DOWNTO 0);
						  constant d : IN NATURAL; constant msg : IN string) is
		begin
			chk(h = seg7(d), msg & " (expected digit " & integer'image(d) & ")");
		end procedure chk_hex;

		procedure wait_ledr(constant exp : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
							constant tmo : IN NATURAL;
							constant msg : IN string) is
			variable c : natural := 0;
		begin
			while ledr /= exp and c < tmo loop
				wait until falling_edge(clk);
				c := c + 1;
			end loop;
			chk(ledr = exp, msg & ": LEDR=" & to_hstring(ledr) &
				", expected " & to_hstring(exp));
		end procedure wait_ledr;

		procedure measure_pwm(constant exp_hi : IN NATURAL;
							  constant exp_lo : IN NATURAL;
							  constant tag    : IN string) is
			variable c, hi, lo : natural;
		begin
			c := 0;
			while pwm /= '0' and c < 20000 loop
				wait until falling_edge(clk); c := c + 1;
			end loop;
			while pwm /= '1' and c < 20000 loop
				wait until falling_edge(clk); c := c + 1;
			end loop;
			chk(c < 20000, tag & ": PWM_o never reached a rising edge");
			c := 0;
			while pwm = '1' and c < 20000 loop
				wait until falling_edge(clk); c := c + 1;
			end loop;
			while pwm = '0' and c < 20000 loop
				wait until falling_edge(clk); c := c + 1;
			end loop;
			chk(c < 20000, tag & ": PWM_o stuck during the skipped period");
			for rep in 1 to 2 loop
				hi := 0; lo := 0;
				while pwm = '1' and hi < 12000 loop
					wait until falling_edge(clk); hi := hi + 1;
				end loop;
				while pwm = '0' and lo < 12000 loop
					wait until falling_edge(clk); lo := lo + 1;
				end loop;
				chk(hi = exp_hi, tag & " period " & integer'image(rep) &
					": high " & integer'image(hi) & " pclk, expected " &
					integer'image(exp_hi));
				chk(lo = exp_lo, tag & " period " & integer'image(rep) &
					": low "  & integer'image(lo) & " pclk, expected " &
					integer'image(exp_lo));
			end loop;
		end procedure measure_pwm;

	begin
		wait until rst = '0';
		settle(4000);

		chk_hex(hex5, 0, "init HEX5"); chk_hex(hex4, 0, "init HEX4");
		chk_hex(hex3, 0, "init HEX3"); chk_hex(hex2, 0, "init HEX2");
		chk_hex(hex1, 0, "init HEX1"); chk_hex(hex0, 0, "init HEX0");
		chk(ledr = x"00", "init LEDR not clear");
		chk(not pwm_seen, "PWM_o pulsed before any KEY1 press");

		press(1);
		wait_ledr(x"01", 8000, "KEY1 #1 Mode0");
		chk_hex(hex0, 0, "Mode0 HEX0");
		chk(ledr = x"01", "Mode0 LEDR");
		measure_pwm(2000, 2008, "Mode0 Set/Reset duty 0.5");

		press(1);
		wait_ledr(x"02", 8000, "KEY1 #2 Mode1");
		chk_hex(hex0, 1, "Mode1 HEX0");
		chk(ledr = x"02", "Mode1 LEDR");
		measure_pwm(2008, 2000, "Mode1 Reset/Set duty 0.5");

		press(1);
		wait_ledr(x"04", 8000, "KEY1 #3 Toggle");
		chk_hex(hex0, 2, "Toggle HEX0");
		chk(ledr = x"04", "Toggle LEDR");
		measure_pwm(4008, 4008, "Toggle at BTCL1");

		press(1);
		wait_ledr(x"01", 8000, "KEY1 #4 wrap to Mode0");
		chk_hex(hex0, 0, "wrap HEX0");

		report "" severity note;
		report "========= PWM MODES (custom KEY1 demo) SUMMARY =========" severity note;
		report "  checks passed " & integer'image(p) & ", failed " &
			integer'image(f) severity note;
		if f = 0 then
			report "  VERDICT: PASS - KEY1 cycled Mode0, Mode1 and Toggle; " &
				"HEX0/LEDR matched; PWM_o widths were 2000/2008, 2008/2000 " &
				"and 4008/4008 pclk." severity note;
		else
			report "  VERDICT: FAIL - " & integer'image(f) & " failure(s)."
				severity note;
		end if;
		report "========================================================" severity note;

		running <= FALSE;
		wait for CLK_PERIOD;
		if f = 0 then std.env.stop(0); else std.env.stop(1); end if;
		wait;
	end process stim;

END test;
