--============================================================================
-- gpio_expected_pkg — GENERATED by tools/gen_gpio_test.py. Do not edit by hand.
--
-- The complete expected store sequence of the directed GPIO test, in bus order.
-- It closes gaps G-406 and G-407, which Phases 6A and 6B each registered against
-- their own verification:
--   G-406  tb_gpio's cross-talk check is one-sided, because GPIO test0 writes the
--          same value to all seven ports in ascending address order.
--   G-407  the seven GPO read-back tri-states of Figure 5 are exercised by no
--          supplied benchmark.
-- They close each other: read-back makes a port's content observable, and that
-- makes the lane decode discriminable in BOTH directions.
--
-- ADDRESSES HERE ARE FULL 14-BIT BYTE ADDRESSES, not DTCM word indices. That
-- matters: an MMIO store to 0x2004 and a DTCM store to word 1 produce the same
-- dtcm_addr_o, so the testbench compares alu_res_o instead.
--
-- EVERY ENTRY MUST MATCH. The program uses only addi, slli, sw, lw at offset
-- zero, and one beq sentinel.
--
-- Derived twice and cross-checked before this file was written: once while
-- emitting the code, once by executing it on an interpreter with an independent
-- model of the GPIO block. Generation aborts if the two disagree.
--============================================================================
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

package gpio_expected_pkg is

	constant NAME_LEN : natural := 29;

	type expected_t is record
		addr	: natural;						-- full byte address on the data bus
		data	: STD_LOGIC_VECTOR(31 DOWNTO 0);
		name	: string(1 to NAME_LEN);
	end record;

	type expected_array_t is array (natural range <>) of expected_t;

	constant STORE_COUNT : natural := 35;

	-- What the testbench must drive on SW_i for the port_sw case to pass.
	-- 0x5C is deliberately not bit-symmetric.
	constant SW_VALUE : STD_LOGIC_VECTOR(7 DOWNTO 0) := x"5C";

	-- What the testbench must drive on KEY_i -- the RAW, active-low pins, indexed
	-- 3 DOWNTO 1. (KEY3, KEY2, KEY1) = (001), i.e. KEY3 and KEY2 pressed,
	-- KEY1 released, so PORT_PB must read 0x06.
	constant KEY_VALUE : STD_LOGIC_VECTOR(3 DOWNTO 1) := "001";

	constant EXPECTED : expected_array_t(0 to STORE_COUNT-1) := (
		(16#0000#, x"DEADBEEF", "alias_marker:dwr             "),	--  0 dtcm store
		(16#2004#, x"000000A5", "hex01_ascending:wr           "),	--  1 mmio store
		(16#2005#, x"0000005A", "hex01_ascending:wr           "),	--  2 mmio store
		(16#0320#, x"000000A5", "hex01_ascending:rd           "),	--  3 must be A5, not 5A
		(16#0324#, x"0000005A", "hex01_ascending:rd           "),	--  4 must be 5A
		(16#2005#, x"000000B7", "hex01_descending:wr          "),	--  5 mmio store
		(16#2004#, x"0000007B", "hex01_descending:wr          "),	--  6 mmio store
		(16#0328#, x"0000007B", "hex01_descending:rd          "),	--  7 must be 7B
		(16#032C#, x"000000B7", "hex01_descending:rd          "),	--  8 must be B7, not 7B
		(16#2008#, x"000000C3", "hex23_both_orders:wr         "),	--  9 mmio store
		(16#2009#, x"0000003C", "hex23_both_orders:wr         "),	-- 10 mmio store
		(16#0330#, x"000000C3", "hex23_both_orders:rd         "),	-- 11 must be C3
		(16#0334#, x"0000003C", "hex23_both_orders:rd         "),	-- 12 must be 3C
		(16#2009#, x"000000D9", "hex23_both_orders:wr         "),	-- 13 mmio store
		(16#2008#, x"0000009D", "hex23_both_orders:wr         "),	-- 14 mmio store
		(16#0338#, x"0000009D", "hex23_both_orders:rd         "),	-- 15 must be 9D
		(16#033C#, x"000000D9", "hex23_both_orders:rd         "),	-- 16 must be D9
		(16#200C#, x"000000E1", "hex45_both_orders:wr         "),	-- 17 mmio store
		(16#200D#, x"0000001E", "hex45_both_orders:wr         "),	-- 18 mmio store
		(16#0340#, x"000000E1", "hex45_both_orders:rd         "),	-- 19 must be E1
		(16#0344#, x"0000001E", "hex45_both_orders:rd         "),	-- 20 must be 1E
		(16#200D#, x"000000F2", "hex45_both_orders:wr         "),	-- 21 mmio store
		(16#200C#, x"0000002F", "hex45_both_orders:wr         "),	-- 22 mmio store
		(16#0348#, x"0000002F", "hex45_both_orders:rd         "),	-- 23 must be 2F
		(16#034C#, x"000000F2", "hex45_both_orders:rd         "),	-- 24 must be F2
		(16#2000#, x"000000FF", "ledr_and_upper_bits:wr       "),	-- 25 mmio store
		(16#0350#, x"000000FF", "ledr_and_upper_bits:rd       "),	-- 26 must be 000000FF, not FFFFFFFF
		(16#0354#, x"0000005C", "port_sw:rd                   "),	-- 27 must be 0000005C
		(16#0358#, x"00000000", "unmapped_read:rd             "),	-- 28 must be 0
		(16#2034#, x"000000AA", "unmapped_write_then_reread:wr"),	-- 29 mmio store
		(16#035C#, x"000000FF", "unmapped_write_then_reread:rd"),	-- 30 must still be 000000FF
		(16#0360#, x"00000006", "port_pb:rd                   "),	-- 31 must be 00000006
		(16#2014#, x"00000000", "port_pb_readonly:wr          "),	-- 32 mmio store
		(16#0364#, x"00000006", "port_pb_readonly:rd          "),	-- 33 must STILL be 00000006
		(16#0368#, x"DEADBEEF", "alias_marker_check:drd       ")	-- 34 must still be DEADBEEF
	);

end package gpio_expected_pkg;
