LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE work.aux_package.all;

ENTITY fpga_hw_interface IS
    PORT (
        CLOCK_50 : IN STD_LOGIC;
        SW       : IN STD_LOGIC_VECTOR(9 DOWNTO 0);
        KEY      : IN STD_LOGIC_VECTOR(3 DOWNTO 0); -- Keys are active LOW on DE2-115
        LEDR     : OUT STD_LOGIC_VECTOR(9 DOWNTO 0);
        HEX0, HEX1, HEX2, HEX3, HEX4, HEX5 : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
        GPIO     : OUT STD_LOGIC_VECTOR(9 DOWNTO 9) -- Using GPIO[9] for PWM output
    );
END fpga_hw_interface;

ARCHITECTURE structural OF fpga_hw_interface IS
    -- Internal Signals for Registers
    SIGNAL Y_reg, X_reg : STD_LOGIC_VECTOR(15 DOWNTO 0) := (OTHERS => '0');
    SIGNAL ALUFN_reg    : STD_LOGIC_VECTOR(4 DOWNTO 0) := (OTHERS => '0');
    
    -- Internal Signals for Digital System Outputs
    SIGNAL ALUout_wire  : STD_LOGIC_VECTOR(7 DOWNTO 0);
    SIGNAL N_wire, C_wire, Z_wire, V_wire : STD_LOGIC;
    SIGNAL PWMout_wire  : STD_LOGIC;
    
    -- 2 MHz system clock generated by the on-chip PLL (Figure 7: 50MHz -> PLL -> 2MHz)
    SIGNAL clk_2MHz   : STD_LOGIC;
    SIGNAL pll_locked : STD_LOGIC;
    
    -- MUX signals for HEX displays
    SIGNAL hex_Y_data, hex_X_data : STD_LOGIC_VECTOR(7 DOWNTO 0);

    -- Active High Key signals for internal logic
    SIGNAL key_pressed : STD_LOGIC_VECTOR(3 DOWNTO 0);

BEGIN
    -- Invert KEYs because DE2-115 pushbuttons are normally HIGH, LOW when pressed
    key_pressed <= NOT KEY;

    -- ==========================================
    -- PLL: 50 MHz -> 2 MHz system clock (Figure 7)
    -- ==========================================
    pll_inst : pll
        PORT MAP (
            areset => '0',
            inclk0 => CLOCK_50,
            c0     => clk_2MHz,
            locked => pll_locked
        );

    -- ==========================================
    -- Input Registers Logic (Triggered by KEYs)
    -- Clocked by the 2 MHz system clock so the whole
    -- digital system lives in a single clock domain.
    -- ==========================================
    PROCESS(clk_2MHz)
    BEGIN
        IF rising_edge(clk_2MHz) THEN
            -- Load Y Register (KEY0)
            IF key_pressed(0) = '1' THEN
                IF SW(9) = '0' THEN
                    Y_reg(15 DOWNTO 8) <= SW(7 DOWNTO 0); -- High 8-bit
                ELSE
                    Y_reg(7 DOWNTO 0) <= SW(7 DOWNTO 0);  -- Low 8-bit
                END IF;
            END IF;
            
            -- Load X Register (KEY1)
            IF key_pressed(1) = '1' THEN
                IF SW(9) = '0' THEN
                    X_reg(15 DOWNTO 8) <= SW(7 DOWNTO 0); -- High 8-bit
                ELSE
                    X_reg(7 DOWNTO 0) <= SW(7 DOWNTO 0);  -- Low 8-bit
                END IF;
            END IF;

            -- Load ALUFN Register (KEY2)
            IF key_pressed(2) = '1' THEN
                ALUFN_reg <= SW(4 DOWNTO 0);
            END IF;
        END IF;
    END PROCESS;

    -- ==========================================
    -- Digital System Instantiation (runs on the 2 MHz PLL clock)
    -- ==========================================
    system_inst : digital_system
        GENERIC MAP (n => 8)
        PORT MAP (
            clk      => clk_2MHz,
            rst      => key_pressed(3), -- KEY3 acts as Reset for PWM
            ena      => SW(8),          -- SW8 acts as Enable for PWM
            Y_i      => Y_reg,
            X_i      => X_reg,
            ALUFN_i  => ALUFN_reg,
            ALUout_o => ALUout_wire,
            Nflag_o  => N_wire,
            Cflag_o  => C_wire,
            Zflag_o  => Z_wire,
            Vflag_o  => V_wire,
            PWMout_o => PWMout_wire
        );

    -- ==========================================
    -- Output Mapping to Physical Board
    -- ==========================================
    -- Map Flags to LEDR3-LEDR0
    LEDR(3) <= N_wire;
    LEDR(2) <= C_wire;
    LEDR(1) <= Z_wire;
    LEDR(0) <= V_wire;
    LEDR(9 DOWNTO 5) <= ALUFN_reg;
    LEDR(4) <= '0';

    -- Map PWM Output
    GPIO(9) <= PWMout_wire;

    -- Multiplexers for HEX Displays based on SW9
    hex_Y_data <= Y_reg(7 DOWNTO 0) WHEN SW(9) = '1' ELSE Y_reg(15 DOWNTO 8);
    hex_X_data <= X_reg(7 DOWNTO 0) WHEN SW(9) = '1' ELSE X_reg(15 DOWNTO 8);

    -- Map HEX Displays (Require 7-segment decoders)
    hex_alu_high : hex_decoder PORT MAP(bin => ALUout_wire(7 DOWNTO 4), seg => HEX5);
    hex_alu_low  : hex_decoder PORT MAP(bin => ALUout_wire(3 DOWNTO 0), seg => HEX4);
    
    hex_y_high   : hex_decoder PORT MAP(bin => hex_Y_data(7 DOWNTO 4), seg => HEX3);
    hex_y_low    : hex_decoder PORT MAP(bin => hex_Y_data(3 DOWNTO 0), seg => HEX2);
    
    hex_x_high   : hex_decoder PORT MAP(bin => hex_X_data(7 DOWNTO 4), seg => HEX1);
    hex_x_low    : hex_decoder PORT MAP(bin => hex_X_data(3 DOWNTO 0), seg => HEX0);

END structural;