#!/usr/bin/env python3
"""Produce the SEPARATELY-MARKED corrected benchmark images -- Phase 10.

THE RULE THIS FILE EXISTS TO HONOUR
    Benchmarks are a contract. The originals under Auxiliary/ are NEVER
    touched; when a supplied benchmark contains a bug, the bug is documented
    (DOC/03) and any corrected copy used for verification is separate and
    clearly marked. This tool derives the corrected copies FROM the originals
    at build time -- each fix is ONE 32-bit word, asserted against the exact
    original value at the exact address, so the provenance of every changed
    bit is mechanical: nothing is hand-hexed, and re-running the tool on a
    changed original ABORTS instead of silently repatching.

THE TWO DOCUMENTED BUGS, AND THE ONE-WORD FIX FOR EACH

  test1 -- EINT is skipped on the SW0=0 (ModelSim / short-delay) path.
    00_main.s:
        bne  t1,zero,if_l        # if SW0='1' -> long delay
        li   a3, short_delay
        j    STATE1              # <-- jumps PAST the EINT below
    if_l:
        li   a3, long_delay
        ori  gp,gp,0x01          # EINT, GIE=gp[0]=1
    With SW0=0, `ori gp,gp,1` never executes: GIE stays 0 and the whole
    KEY-driven application is dead in exactly the configuration its own
    comments call "used for ModelSim based verification". tests 2/3/4 all
    set EINT unconditionally at init -- test1 alone gates it, which marks
    this as a regression, not intent.
    FIX: the `jal x0` at byte 0xBC targets 0xD8 (STATE1); retarget it to
    0xC8 -- the `ori` itself -- so the short path becomes
    li short -> EINT -> STATE0, matching the other three tests' flow. One
    word: 0x01C0006F -> 0x00C0006F. No instruction moves, so the interrupt
    vector table's absolute handler addresses stay valid.

  test4 -- capture never sees an edge (open question Q10 / G-327).
    01_func.s:175 capture_init and :191 capture BOTH write
    CAPMD1_CAPISEL3 = 0x07 to BTCTL2, so CAPISEL never leaves GND and no
    capture event can occur. capture's own comment says "set the input
    signal to VCC" -- the code contradicts its own comment, and Hanan's
    recorded prep session describes the intent as "initialise the select
    to 3, then set it to 2" (DOC/03 section C).
    FIX: in `capture` only (byte 0x424), addi t0,zero,7 -> addi t0,zero,6
    (0x00700293 -> 0x00600293): BTCTL2=0x06 = CAPMD=01 (rising), CAPISEL=10
    (VCC) -- the GND->VCC rising event he described. capture_init's 0x07 at
    byte 0x410 is left exactly as shipped.

OUTPUT
    SIM/RV32IMscMCU/bench_fixed/test1/{ITCM.hex,DTCM.hex}
    SIM/RV32IMscMCU/bench_fixed/test4/{ITCM.hex,DTCM.hex}
    SIM/RV32IMscMCU/bench_fixed/PATCHES.md   (the audit trail)
    DTCM images are copied byte-identical; only the one ITCM word differs.

USAGE
    python3 tools/patch_bench_images.py
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from gen_isa_test import ihex                                # noqa: E402

BENCH = ROOT / "Auxiliary" / "Benchmark Apps" / "Intrrupt-based IO"
OUT = ROOT / "SIM" / "RV32IMscMCU" / "bench_fixed"

# (test, word_index, expected_original, patched, why)
PATCHES = [
    ("test1", 0xBC // 4, 0x01C0006F, 0x00C0006F,
     "jal x0 retargeted 0xD8 (STATE1) -> 0xC8 (the EINT ori): the SW0=0 "
     "short-delay path no longer skips `ori gp,gp,1`"),
    ("test4", 0x424 // 4, 0x00700293, 0x00600293,
     "capture writes BTCTL2=0x06 (CAPMD=01 rising, CAPISEL=10 VCC) instead "
     "of repeating capture_init's 0x07 (GND): the GND->VCC rising event "
     "the function's own comment and the prep session describe"),
]

# guard words that must NOT change (proves the right site was patched)
GUARDS = [
    ("test1", 0xC8 // 4, 0x0011E193, "ori gp,gp,1 -- the EINT the fix lands on"),
    ("test4", 0x410 // 4, 0x00700293, "capture_init's 0x07 -- stays as shipped"),
]


def load_hex(p):
    ws = []
    for ln in p.read_text().splitlines():
        ln = ln.strip()
        if ln.startswith(":04") and ln[7:9] == "00":
            ws.append(int(ln[9:17], 16))
    return ws


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    audit = [
        "# Corrected benchmark images -- generated by tools/patch_bench_images.py",
        "",
        "The originals under `Auxiliary/Benchmark Apps/Intrrupt-based IO/` are",
        "untouched, per the benchmarks-are-a-contract rule. Each image here",
        "differs from its original by EXACTLY ONE 32-bit word, listed below and",
        "asserted against the original value at generation time. DTCM images",
        "are byte-identical copies. Full reasoning: the tool's own header and",
        "DOC/03 (test1: the SW0-gated EINT; test4: Q10 / G-327).",
        "",
        "test4's one word makes the capture EDGE real, and no more than that:",
        "the shipped flow also zeroes BTINT in `capture_init` and holds",
        "BTHOLD=1,BTCLR=1 through the measured window, so no BT interrupt",
        "fires and BTCAPR latches 0 -- runtime_div/runtime_rem stay 0 even",
        "with this fix. Deliberately NOT patched further (question B6 in",
        "DOC/05; details in DOC/03's Q10 update and the plan's Phase 10B).",
        "",
        "| test | byte addr | original | patched | why |",
        "| --- | --- | --- | --- | --- |",
    ]

    for test, wi, orig, new, why in PATCHES:
        src = BENCH / test / "bin" / "M9K-intel"
        ws = load_hex(src / "ITCM.hex")
        if ws[wi] != orig:
            sys.exit(f"ABORT: {test} word {wi} is {ws[wi]:#010x}, expected "
                     f"{orig:#010x} -- the original changed; re-derive the "
                     "patch before regenerating")
        for gt, gwi, gval, gwhy in GUARDS:
            if gt == test and ws[gwi] != gval:
                sys.exit(f"ABORT: {test} guard word {gwi} is {ws[gwi]:#010x}, "
                         f"expected {gval:#010x} ({gwhy})")
        patched = list(ws)
        patched[wi] = new
        diff = [i for i, (a, b) in enumerate(zip(ws, patched)) if a != b]
        assert diff == [wi], "more than one word changed"

        dst = OUT / test
        dst.mkdir(parents=True, exist_ok=True)
        (dst / "ITCM.hex").write_text(ihex(patched))
        (dst / "DTCM.hex").write_bytes((src / "DTCM.hex").read_bytes())
        audit.append(f"| {test} | {wi*4:#06x} | {orig:#010x} | {new:#010x} "
                     f"| {why} |")
        print(f"  {test}: word {wi} ({wi*4:#x}) {orig:#010x} -> {new:#010x}")

    (OUT / "PATCHES.md").write_text("\n".join(audit) + "\n")
    print(f"  wrote {OUT}/ (test1, test4, PATCHES.md)")


if __name__ == "__main__":
    main()
