onerror {resume}
add list -hex -width 18 /tb_datapath/clk
add list -hex /tb_datapath/rst
add list -hex /tb_datapath/IRin
add list -hex /tb_datapath/PCin
add list -hex /tb_datapath/PCsel
add list -hex /tb_datapath/Imm1_in
add list -hex /tb_datapath/Imm2_in
add list -hex /tb_datapath/RFout
add list -hex /tb_datapath/RFin
add list -hex /tb_datapath/RFaddr_wr
add list -hex /tb_datapath/Ain
add list -hex /tb_datapath/Cin
add list -hex /tb_datapath/Cout
add list -hex /tb_datapath/DTCM_addr_in
add list -hex /tb_datapath/DTCM_out
add list -hex /tb_datapath/RFaddr_rd
add list -hex /tb_datapath/ALUFN
add list -hex /tb_datapath/Instruction_in
add list -hex /tb_datapath/DTCM_data_in
add list -hex /tb_datapath/Cflag
add list -hex /tb_datapath/Zflag
add list -hex /tb_datapath/Nflag
add list -hex /tb_datapath/PC_out_addr
add list -hex /tb_datapath/DTCM_data_out
add list -hex /tb_datapath/DTCM_addr
add list -hex /tb_datapath/uut/clk
add list -hex /tb_datapath/uut/rst
add list -hex /tb_datapath/uut/IRin
add list -hex /tb_datapath/uut/PCin
add list -hex /tb_datapath/uut/PCsel
add list -hex /tb_datapath/uut/Imm1_in
add list -hex /tb_datapath/uut/Imm2_in
add list -hex /tb_datapath/uut/RFout
add list -hex /tb_datapath/uut/RFin
add list -hex /tb_datapath/uut/RFaddr_rd
add list -hex /tb_datapath/uut/RFaddr_wr
add list -hex /tb_datapath/uut/Ain
add list -hex /tb_datapath/uut/Cin
add list -hex /tb_datapath/uut/Cout
add list -hex /tb_datapath/uut/ALUFN
add list -hex /tb_datapath/uut/DTCM_addr_in
add list -hex /tb_datapath/uut/DTCM_out
add list -hex /tb_datapath/uut/OPC_out
add list -hex /tb_datapath/uut/Cflag
add list -hex /tb_datapath/uut/Zflag
add list -hex /tb_datapath/uut/Nflag
add list -hex /tb_datapath/uut/Instruction_in
add list -hex /tb_datapath/uut/PC_out_addr
add list -hex /tb_datapath/uut/DTCM_data_in
add list -hex /tb_datapath/uut/DTCM_data_out
add list -hex /tb_datapath/uut/DTCM_addr
add list -hex /tb_datapath/uut/Main_BUS
add list -hex /tb_datapath/uut/PC_reg
add list -hex /tb_datapath/uut/IR_reg
add list -hex /tb_datapath/uut/A_reg
add list -hex /tb_datapath/uut/C_reg
add list -hex /tb_datapath/uut/DTCM_addr_reg
add list -hex /tb_datapath/uut/Cflag_reg
add list -hex /tb_datapath/uut/Zflag_reg
add list -hex /tb_datapath/uut/Nflag_reg
add list -hex /tb_datapath/uut/RF_RregAddr
add list -hex /tb_datapath/uut/RF_WregAddr
add list -hex /tb_datapath/uut/RF_RregData
add list -hex /tb_datapath/uut/ALU_out
add list -hex /tb_datapath/uut/ALU_Cout
configure list -usestrobe 0
configure list -strobestart {0 ps} -strobeperiod {0 ps}
configure list -usesignaltrigger 1
configure list -delta all
configure list -signalnamewidth 0
configure list -datasetprefix 0
configure list -namelimit 5
